export type VerbCaseKey = "acc" | "dat";

export type VerbQuestion = {
  id: number;
  before: string;
  after: string;
  answer: string;
  reflexiveAnswer: string | null;
  preposition: string;
  caseKey: VerbCaseKey;
  patternId: string;
  frame: string;
  verb: string;
  tense: "Präsens" | "Perfekt" | "Futur I" | "Konjunktiv II";
  isQuestion: boolean;
};

type VerbPattern = {
  id: string;
  verb: string;
  frame: string;
  preposition: string;
  caseKey: VerbCaseKey;
  reflexive: boolean;
  infinitive: string;
  presentIch: string;
  presentDu: string;
  participle: string;
  presentTail?: string;
  objects: [string, string, string, string, string];
};

export const REFLEXIVE_CHOICES = ["mich", "dich", "sich", "uns", "euch"] as const;
export const PREPOSITION_CHOICES = [
  "an",
  "auf",
  "für",
  "gegen",
  "mit",
  "nach",
  "über",
  "um",
  "unter",
  "von",
  "vor",
  "zu",
] as const;

const PATTERNS: VerbPattern[] = [
  {
    id: "denken-an",
    verb: "denken",
    frame: "denken an + Akk",
    preposition: "an",
    caseKey: "acc",
    reflexive: false,
    infinitive: "denken",
    presentIch: "denke",
    presentDu: "denkst",
    participle: "gedacht",
    objects: ["meine Prüfung", "unsere erste Reise", "deinen Vorschlag", "seine Familie", "die Folgen"],
  },
  {
    id: "warten-auf",
    verb: "warten",
    frame: "warten auf + Akk",
    preposition: "auf",
    caseKey: "acc",
    reflexive: false,
    infinitive: "warten",
    presentIch: "warte",
    presentDu: "wartest",
    participle: "gewartet",
    objects: ["den Bus", "eine Antwort", "deine Schwester", "das Ergebnis", "den richtigen Moment"],
  },
  {
    id: "sprechen-ueber",
    verb: "sprechen",
    frame: "sprechen über + Akk",
    preposition: "über",
    caseKey: "acc",
    reflexive: false,
    infinitive: "sprechen",
    presentIch: "spreche",
    presentDu: "sprichst",
    participle: "gesprochen",
    objects: ["das neue Projekt", "unsere Pläne", "diesen Film", "seine Entscheidung", "eure Erfahrungen"],
  },
  {
    id: "sprechen-mit",
    verb: "sprechen",
    frame: "sprechen mit + Dat",
    preposition: "mit",
    caseKey: "dat",
    reflexive: false,
    infinitive: "sprechen",
    presentIch: "spreche",
    presentDu: "sprichst",
    participle: "gesprochen",
    objects: ["meinem Nachbarn", "einer Ärztin", "deinem Chef", "seinen Eltern", "den neuen Kollegen"],
  },
  {
    id: "teilnehmen-an",
    verb: "teilnehmen",
    frame: "teilnehmen an + Dat",
    preposition: "an",
    caseKey: "dat",
    reflexive: false,
    infinitive: "teilnehmen",
    presentIch: "nehme",
    presentDu: "nimmst",
    participle: "teilgenommen",
    presentTail: " teil",
    objects: ["einem Sprachkurs", "der Besprechung", "diesem Wettbewerb", "einer Konferenz", "den Übungen"],
  },
  {
    id: "traeumen-von",
    verb: "träumen",
    frame: "träumen von + Dat",
    preposition: "von",
    caseKey: "dat",
    reflexive: false,
    infinitive: "träumen",
    presentIch: "träume",
    presentDu: "träumst",
    participle: "geträumt",
    objects: ["einem Haus am Meer", "unserem Urlaub", "deiner Zukunft", "einer langen Reise", "besseren Zeiten"],
  },
  {
    id: "fragen-nach",
    verb: "fragen",
    frame: "fragen nach + Dat",
    preposition: "nach",
    caseKey: "dat",
    reflexive: false,
    infinitive: "fragen",
    presentIch: "frage",
    presentDu: "fragst",
    participle: "gefragt",
    objects: ["dem Weg", "einem freien Termin", "deiner Meinung", "dem Preis", "den Öffnungszeiten"],
  },
  {
    id: "bitten-um",
    verb: "bitten",
    frame: "bitten um + Akk",
    preposition: "um",
    caseKey: "acc",
    reflexive: false,
    infinitive: "bitten",
    presentIch: "bitte",
    presentDu: "bittest",
    participle: "gebeten",
    objects: ["einen Rat", "mehr Zeit", "deine Hilfe", "eine kurze Pause", "Verständnis"],
  },
  {
    id: "danken-fuer",
    verb: "danken",
    frame: "danken für + Akk",
    preposition: "für",
    caseKey: "acc",
    reflexive: false,
    infinitive: "danken",
    presentIch: "danke",
    presentDu: "dankst",
    participle: "gedankt",
    objects: ["deine Nachricht", "das schöne Geschenk", "diesen Hinweis", "seine Unterstützung", "eure Geduld"],
  },
  {
    id: "gehoeren-zu",
    verb: "gehören",
    frame: "gehören zu + Dat",
    preposition: "zu",
    caseKey: "dat",
    reflexive: false,
    infinitive: "gehören",
    presentIch: "gehöre",
    presentDu: "gehörst",
    participle: "gehört",
    objects: ["dieser Gruppe", "unserem Team", "deiner Familie", "dem neuen System", "den wichtigsten Regeln"],
  },
  {
    id: "rechnen-mit",
    verb: "rechnen",
    frame: "rechnen mit + Dat",
    preposition: "mit",
    caseKey: "dat",
    reflexive: false,
    infinitive: "rechnen",
    presentIch: "rechne",
    presentDu: "rechnest",
    participle: "gerechnet",
    objects: ["einer Verspätung", "starkem Regen", "deiner Zustimmung", "einem schwierigen Gespräch", "weiteren Kosten"],
  },
  {
    id: "glauben-an",
    verb: "glauben",
    frame: "glauben an + Akk",
    preposition: "an",
    caseKey: "acc",
    reflexive: false,
    infinitive: "glauben",
    presentIch: "glaube",
    presentDu: "glaubst",
    participle: "geglaubt",
    objects: ["diese Idee", "unseren Erfolg", "deine Geschichte", "eine bessere Zukunft", "eure Fähigkeiten"],
  },
  {
    id: "hoffen-auf",
    verb: "hoffen",
    frame: "hoffen auf + Akk",
    preposition: "auf",
    caseKey: "acc",
    reflexive: false,
    infinitive: "hoffen",
    presentIch: "hoffe",
    presentDu: "hoffst",
    participle: "gehofft",
    objects: ["gutes Wetter", "eine schnelle Lösung", "deine Rückkehr", "den Sieg", "ruhige Tage"],
  },
  {
    id: "leiden-unter",
    verb: "leiden",
    frame: "leiden unter + Dat",
    preposition: "unter",
    caseKey: "dat",
    reflexive: false,
    infinitive: "leiden",
    presentIch: "leide",
    presentDu: "leidest",
    participle: "gelitten",
    objects: ["dem Lärm", "großem Stress", "dieser Unsicherheit", "einer Allergie", "den hohen Preisen"],
  },
  {
    id: "warnen-vor",
    verb: "warnen",
    frame: "warnen vor + Dat",
    preposition: "vor",
    caseKey: "dat",
    reflexive: false,
    infinitive: "warnen",
    presentIch: "warne",
    presentDu: "warnst",
    participle: "gewarnt",
    objects: ["der Gefahr", "einem Fehler", "dieser Straße", "dem starken Wind", "falschen Versprechen"],
  },
  {
    id: "gratulieren-zu",
    verb: "gratulieren",
    frame: "gratulieren zu + Dat",
    preposition: "zu",
    caseKey: "dat",
    reflexive: false,
    infinitive: "gratulieren",
    presentIch: "gratuliere",
    presentDu: "gratulierst",
    participle: "gratuliert",
    objects: ["deinem Geburtstag", "der bestandenen Prüfung", "diesem Erfolg", "seiner Beförderung", "euren Ergebnissen"],
  },
  {
    id: "verzichten-auf",
    verb: "verzichten",
    frame: "verzichten auf + Akk",
    preposition: "auf",
    caseKey: "acc",
    reflexive: false,
    infinitive: "verzichten",
    presentIch: "verzichte",
    presentDu: "verzichtest",
    participle: "verzichtet",
    objects: ["Zucker", "das Auto", "deinen freien Abend", "eine lange Pause", "unnötige Verpackungen"],
  },
  {
    id: "erzaehlen-von",
    verb: "erzählen",
    frame: "erzählen von + Dat",
    preposition: "von",
    caseKey: "dat",
    reflexive: false,
    infinitive: "erzählen",
    presentIch: "erzähle",
    presentDu: "erzählst",
    participle: "erzählt",
    objects: ["meiner Kindheit", "einem seltsamen Traum", "deiner Reise", "seinem neuen Job", "alten Zeiten"],
  },
  {
    id: "kaempfen-fuer",
    verb: "kämpfen",
    frame: "kämpfen für + Akk",
    preposition: "für",
    caseKey: "acc",
    reflexive: false,
    infinitive: "kämpfen",
    presentIch: "kämpfe",
    presentDu: "kämpfst",
    participle: "gekämpft",
    objects: ["meine Rechte", "eine faire Lösung", "deinen Traum", "den Klassenerhalt", "bessere Bedingungen"],
  },
  {
    id: "protestieren-gegen",
    verb: "protestieren",
    frame: "protestieren gegen + Akk",
    preposition: "gegen",
    caseKey: "acc",
    reflexive: false,
    infinitive: "protestieren",
    presentIch: "protestiere",
    presentDu: "protestierst",
    participle: "protestiert",
    objects: ["diese Entscheidung", "den neuen Plan", "deine Kündigung", "das Verbot", "höhere Gebühren"],
  },
  {
    id: "sich-kuemmern-um",
    verb: "sich kümmern",
    frame: "sich kümmern um + Akk",
    preposition: "um",
    caseKey: "acc",
    reflexive: true,
    infinitive: "kümmern",
    presentIch: "kümmere",
    presentDu: "kümmerst",
    participle: "gekümmert",
    objects: ["den Einkauf", "unsere Gäste", "deinen Hund", "das Abendessen", "die letzten Details"],
  },
  {
    id: "sich-erinnern-an",
    verb: "sich erinnern",
    frame: "sich erinnern an + Akk",
    preposition: "an",
    caseKey: "acc",
    reflexive: true,
    infinitive: "erinnern",
    presentIch: "erinnere",
    presentDu: "erinnerst",
    participle: "erinnert",
    objects: ["meinen ersten Schultag", "unser Gespräch", "diesen Namen", "seine alte Wohnung", "eure gemeinsame Reise"],
  },
  {
    id: "sich-interessieren-fuer",
    verb: "sich interessieren",
    frame: "sich interessieren für + Akk",
    preposition: "für",
    caseKey: "acc",
    reflexive: true,
    infinitive: "interessieren",
    presentIch: "interessiere",
    presentDu: "interessierst",
    participle: "interessiert",
    objects: ["moderne Kunst", "diese Stelle", "dein Hobby", "das neue Angebot", "politische Geschichte"],
  },
  {
    id: "sich-freuen-auf",
    verb: "sich freuen",
    frame: "sich freuen auf + Akk",
    preposition: "auf",
    caseKey: "acc",
    reflexive: true,
    infinitive: "freuen",
    presentIch: "freue",
    presentDu: "freust",
    participle: "gefreut",
    objects: ["das Wochenende", "unseren Besuch", "deinen Geburtstag", "die nächste Saison", "eure Ankunft"],
  },
  {
    id: "sich-freuen-ueber",
    verb: "sich freuen",
    frame: "sich freuen über + Akk",
    preposition: "über",
    caseKey: "acc",
    reflexive: true,
    infinitive: "freuen",
    presentIch: "freue",
    presentDu: "freust",
    participle: "gefreut",
    objects: ["das Geschenk", "unsere Fortschritte", "deine Nachricht", "den unerwarteten Besuch", "eure guten Noten"],
  },
  {
    id: "sich-aergern-ueber",
    verb: "sich ärgern",
    frame: "sich ärgern über + Akk",
    preposition: "über",
    caseKey: "acc",
    reflexive: true,
    infinitive: "ärgern",
    presentIch: "ärgere",
    presentDu: "ärgerst",
    participle: "geärgert",
    objects: ["den Lärm", "unsere Verspätung", "deinen Kommentar", "das schlechte Ergebnis", "unnötige Fehler"],
  },
  {
    id: "sich-vorbereiten-auf",
    verb: "sich vorbereiten",
    frame: "sich vorbereiten auf + Akk",
    preposition: "auf",
    caseKey: "acc",
    reflexive: true,
    infinitive: "vorbereiten",
    presentIch: "bereite",
    presentDu: "bereitest",
    participle: "vorbereitet",
    presentTail: " vor",
    objects: ["die Prüfung", "unseren Umzug", "dein Interview", "das wichtige Gespräch", "schwierige Fragen"],
  },
  {
    id: "sich-bewerben-um",
    verb: "sich bewerben",
    frame: "sich bewerben um + Akk",
    preposition: "um",
    caseKey: "acc",
    reflexive: true,
    infinitive: "bewerben",
    presentIch: "bewerbe",
    presentDu: "bewirbst",
    participle: "beworben",
    objects: ["die Stelle", "einen Studienplatz", "dieses Stipendium", "den Ausbildungsplatz", "mehrere Projekte"],
  },
  {
    id: "sich-entscheiden-fuer",
    verb: "sich entscheiden",
    frame: "sich entscheiden für + Akk",
    preposition: "für",
    caseKey: "acc",
    reflexive: true,
    infinitive: "entscheiden",
    presentIch: "entscheide",
    presentDu: "entscheidest",
    participle: "entschieden",
    objects: ["den Zug", "eine kleinere Wohnung", "deinen Vorschlag", "das blaue Modell", "flexible Arbeitszeiten"],
  },
  {
    id: "sich-entschuldigen-fuer",
    verb: "sich entschuldigen",
    frame: "sich entschuldigen für + Akk",
    preposition: "für",
    caseKey: "acc",
    reflexive: true,
    infinitive: "entschuldigen",
    presentIch: "entschuldige",
    presentDu: "entschuldigst",
    participle: "entschuldigt",
    objects: ["meinen Fehler", "unsere Verspätung", "deine Worte", "das Missverständnis", "die kurzfristige Absage"],
  },
  {
    id: "sich-erkundigen-nach",
    verb: "sich erkundigen",
    frame: "sich erkundigen nach + Dat",
    preposition: "nach",
    caseKey: "dat",
    reflexive: true,
    infinitive: "erkundigen",
    presentIch: "erkundige",
    presentDu: "erkundigst",
    participle: "erkundigt",
    objects: ["dem Fahrplan", "einem freien Zimmer", "deiner Adresse", "dem aktuellen Stand", "günstigen Angeboten"],
  },
  {
    id: "sich-konzentrieren-auf",
    verb: "sich konzentrieren",
    frame: "sich konzentrieren auf + Akk",
    preposition: "auf",
    caseKey: "acc",
    reflexive: true,
    infinitive: "konzentrieren",
    presentIch: "konzentriere",
    presentDu: "konzentrierst",
    participle: "konzentriert",
    objects: ["meine Aufgabe", "das Wesentliche", "deine Aussprache", "den nächsten Schritt", "wichtige Details"],
  },
  {
    id: "sich-beschaeftigen-mit",
    verb: "sich beschäftigen",
    frame: "sich beschäftigen mit + Dat",
    preposition: "mit",
    caseKey: "dat",
    reflexive: true,
    infinitive: "beschäftigen",
    presentIch: "beschäftige",
    presentDu: "beschäftigst",
    participle: "beschäftigt",
    objects: ["deutscher Geschichte", "diesem Problem", "deiner Frage", "dem neuen Konzept", "aktuellen Studien"],
  },
  {
    id: "sich-treffen-mit",
    verb: "sich treffen",
    frame: "sich treffen mit + Dat",
    preposition: "mit",
    caseKey: "dat",
    reflexive: true,
    infinitive: "treffen",
    presentIch: "treffe",
    presentDu: "triffst",
    participle: "getroffen",
    objects: ["meiner Schwester", "alten Freunden", "deinem Trainer", "einem Kunden", "den neuen Nachbarn"],
  },
  {
    id: "sich-unterhalten-ueber",
    verb: "sich unterhalten",
    frame: "sich unterhalten über + Akk",
    preposition: "über",
    caseKey: "acc",
    reflexive: true,
    infinitive: "unterhalten",
    presentIch: "unterhalte",
    presentDu: "unterhältst",
    participle: "unterhalten",
    objects: ["den Urlaub", "unsere Zukunft", "deinen neuen Job", "das letzte Spiel", "gemeinsame Pläne"],
  },
  {
    id: "sich-wundern-ueber",
    verb: "sich wundern",
    frame: "sich wundern über + Akk",
    preposition: "über",
    caseKey: "acc",
    reflexive: true,
    infinitive: "wundern",
    presentIch: "wundere",
    presentDu: "wunderst",
    participle: "gewundert",
    objects: ["seine Reaktion", "das Ergebnis", "deine Ruhe", "den hohen Preis", "diese Unterschiede"],
  },
  {
    id: "sich-schuetzen-vor",
    verb: "sich schützen",
    frame: "sich schützen vor + Dat",
    preposition: "vor",
    caseKey: "dat",
    reflexive: true,
    infinitive: "schützen",
    presentIch: "schütze",
    presentDu: "schützt",
    participle: "geschützt",
    objects: ["der Sonne", "kaltem Wind", "dieser Krankheit", "dem Lärm", "unerwarteten Kosten"],
  },
  {
    id: "sich-gewoehnen-an",
    verb: "sich gewöhnen",
    frame: "sich gewöhnen an + Akk",
    preposition: "an",
    caseKey: "acc",
    reflexive: true,
    infinitive: "gewöhnen",
    presentIch: "gewöhne",
    presentDu: "gewöhnst",
    participle: "gewöhnt",
    objects: ["den neuen Rhythmus", "das frühe Aufstehen", "deine Nachbarn", "die kalten Winter", "lange Arbeitstage"],
  },
  {
    id: "sich-verlassen-auf",
    verb: "sich verlassen",
    frame: "sich verlassen auf + Akk",
    preposition: "auf",
    caseKey: "acc",
    reflexive: true,
    infinitive: "verlassen",
    presentIch: "verlasse",
    presentDu: "verlässt",
    participle: "verlassen",
    objects: ["meine Erfahrung", "unseren Plan", "dein Versprechen", "seine Hilfe", "klare Regeln"],
  },
  {
    id: "sich-bedanken-fuer",
    verb: "sich bedanken",
    frame: "sich bedanken für + Akk",
    preposition: "für",
    caseKey: "acc",
    reflexive: true,
    infinitive: "bedanken",
    presentIch: "bedanke",
    presentDu: "bedankst",
    participle: "bedankt",
    objects: ["die Einladung", "eure Unterstützung", "deine Geduld", "das nette Gespräch", "hilfreiche Rückmeldungen"],
  },
];

function capitalize(value: string) {
  return value.charAt(0).toUpperCase() + value.slice(1);
}

function answerFor(pattern: VerbPattern, reflexiveAnswer: string | null) {
  return pattern.reflexive ? `${reflexiveAnswer} ${pattern.preposition}` : pattern.preposition;
}

function createQuestions(pattern: VerbPattern, patternIndex: number): VerbQuestion[] {
  const startId = patternIndex * 5 + 1;
  const tail = pattern.presentTail ?? "";
  const make = (
    offset: number,
    before: string,
    after: string,
    reflexiveAnswer: string | null,
    tense: VerbQuestion["tense"],
    isQuestion = false,
  ): VerbQuestion => ({
    id: startId + offset,
    before,
    after,
    answer: answerFor(pattern, reflexiveAnswer),
    reflexiveAnswer: pattern.reflexive ? reflexiveAnswer : null,
    preposition: pattern.preposition,
    caseKey: pattern.caseKey,
    patternId: pattern.id,
    frame: pattern.frame,
    verb: pattern.verb,
    tense,
    isQuestion,
  });

  return [
    make(0, `Ich ${pattern.presentIch} `, ` ${pattern.objects[0]}${tail}.`, "mich", "Präsens"),
    make(1, "Wir haben ", ` ${pattern.objects[1]} ${pattern.participle}.`, "uns", "Perfekt"),
    make(2, `${capitalize(pattern.presentDu)} du `, ` ${pattern.objects[2]}${tail}?`, "dich", "Präsens", true),
    make(3, "Morgen wird er ", ` ${pattern.objects[3]} ${pattern.infinitive}.`, "sich", "Futur I"),
    make(4, "Ihr solltet ", ` ${pattern.objects[4]} ${pattern.infinitive}.`, "euch", "Konjunktiv II"),
  ];
}

export const VERB_PATTERNS = PATTERNS.map(({ id, verb, frame, preposition, caseKey, reflexive }) => ({
  id,
  verb,
  frame,
  preposition,
  caseKey,
  reflexive,
}));

export const VERB_QUESTIONS = PATTERNS.flatMap(createQuestions);

if (VERB_QUESTIONS.length !== 200) {
  throw new Error(`Expected 200 verb-governance questions, received ${VERB_QUESTIONS.length}.`);
}
