import { ELanguage } from "../shared/model";

export const APP_COPY = {
  [ELanguage.Russian]: {
    homeEyebrow: "ТВОЯ АРЕНА НЕМЕЦКОГО",
    homeTitleStart: "Выбери своего",
    homeTitleAccent: "противника.",
    homeSubtitle:
      "Немецкий любит выставлять правила как боссов. Разбираем их по одному — короткими забегами, без зубрёжки таблиц.",
    trainers: "Тренажёры",
    available: "доступно",
    adjectiveTitle: "Окончания прилагательных",
    adjectiveDescription:
      "Ставь правильную форму в живом предложении и сразу разбирай грамматический сигнал.",
    verbTitle: "Предлоги и возвратность",
    verbDescription:
      "Собирай глагол вместе с нужным предлогом, падежом и возвратным местоимением.",
    participleTitle: "Partizip II",
    participleDescription:
      "Доводи формы частотных глаголов до автоматизма в разных временах, вопросах и придаточных.",
    enterArena: "В бой",
    moreSoon: "Новые противники появятся здесь позже.",
    home: "Все тренажёры",
    stats: "Статистика",
    statsTitle: "Статистика окончаний",
    statsSubtitle: "Все ответы в разрезе падежа, рода и типа артикля.",
    statsBreakdown: "Падеж × род",
    articleType: "Тип артикля",
    answersShort: "отв.",
    totalAnswers: "всего ответов",
    totalCorrect: "правильно",
    totalMistakes: "ошибок",
    noAnswers: "Ответов пока нет",
    noAnswersHint:
      "Реши хотя бы одно задание — и здесь появится первая ячейка.",
    correctShort: "верно",
    mistakesShort: "ошибок",
    statsNote:
      "Статистика хранится только на этом устройстве и обновляется после каждого ответа.",
    closeStats: "Закрыть статистику",
    tagline: "Победи окончания немецких прилагательных.",
    run: "забег",
    streak: "серия",
    wordMode: "слово",
    endingMode: "окончание",
    adjective: "исходное прилагательное",
    placeholder: "Введи форму целиком",
    check: "Проверить",
    choose: "Выбери окончание",
    correct: "Точно!",
    wrong: "Почти. Нужна другая форма.",
    yourAnswer: "Твой ответ",
    next: "Дальше",
    finish: "Результат",
    mixedNote: "Все падежи · все артикли · без подсказок по теме",
    resultTitle: "Забег завершён.",
    resultSubtitle: "Вот как прошли эти десять заданий.",
    accuracy: "точность",
    bestStreak: "лучшая серия",
    weakSpot: "Потренировать дальше",
    again: "Ещё один забег",
    lifetime: "Всего правильных ответов",
    definite: "der-слово",
    ein: "ein-слово",
    quantity: "слово количества",
    zero: "без артикля",
    nom: "Nominativ",
    acc: "Akkusativ",
    dat: "Dativ",
    gen: "Genitiv",
    m: "мужской род",
    f: "женский род",
    n: "средний род",
    pl: "множественное число",
    ruleDefinite: (ending: string) =>
      `Слово перед прилагательным работает по модели определённого артикля и уже несёт грамматический сигнал. Поэтому прилагательное получает -${ending}.`,
    ruleEin: (ending: string) =>
      `Слово перед прилагательным работает по модели неопределённого артикля. В этой форме прилагательное получает -${ending}.`,
    ruleQuantity: (ending: string) =>
      `Перед существительным стоит слово количества. В этой форме прилагательное получает -${ending}.`,
    ruleZero: (ending: string) =>
      `Артикля нет, поэтому прилагательное само несёт грамматический сигнал: -${ending}.`,
  },
  [ELanguage.English]: {
    homeEyebrow: "YOUR GERMAN TRAINING ARENA",
    homeTitleStart: "Choose your next",
    homeTitleAccent: "opponent.",
    homeSubtitle:
      "German likes to turn rules into boss fights. We take them down one at a time — in quick runs, without memorising tables.",
    trainers: "Trainers",
    available: "ready",
    adjectiveTitle: "Adjective endings",
    adjectiveDescription:
      "Build the right form inside a real sentence and see the grammar signal immediately.",
    verbTitle: "Prepositions & Reflexive Verbs",
    verbDescription:
      "Build German verb patterns with the right preposition, case, and reflexive pronoun.",
    participleTitle: "Partizip II",
    participleDescription:
      "Automate the participles of frequent verbs across tenses, questions, and subordinate clauses.",
    enterArena: "Enter arena",
    moreSoon: "New opponents will appear here later.",
    home: "All trainers",
    stats: "Statistics",
    statsTitle: "Ending statistics",
    statsSubtitle:
      "All answers broken down by case, gender, and article type.",
    statsBreakdown: "Case × gender",
    articleType: "Article type",
    answersShort: "ans.",
    totalAnswers: "total answers",
    totalCorrect: "correct",
    totalMistakes: "mistakes",
    noAnswers: "No answers yet",
    noAnswersHint:
      "Complete at least one exercise and your first cell will appear here.",
    correctShort: "correct",
    mistakesShort: "mistakes",
    statsNote:
      "Statistics stay on this device and update after every answer.",
    closeStats: "Close statistics",
    tagline: "Beat German adjective endings.",
    run: "run",
    streak: "streak",
    wordMode: "full word",
    endingMode: "ending",
    adjective: "base adjective",
    placeholder: "Type the full form",
    check: "Check",
    choose: "Choose the ending",
    correct: "Nailed it!",
    wrong: "Almost. This form needs a fix.",
    yourAnswer: "Your answer",
    next: "Next one",
    finish: "See results",
    mixedNote: "Every case · every article · no topic hints",
    resultTitle: "Run complete.",
    resultSubtitle: "Here is how those ten exercises went.",
    accuracy: "accuracy",
    bestStreak: "best streak",
    weakSpot: "Train this next",
    again: "Start another run",
    lifetime: "Correct answers overall",
    definite: "der-word",
    ein: "ein-word",
    quantity: "quantity word",
    zero: "no article",
    nom: "Nominative",
    acc: "Accusative",
    dat: "Dative",
    gen: "Genitive",
    m: "masculine",
    f: "feminine",
    n: "neuter",
    pl: "plural",
    ruleDefinite: (ending: string) =>
      `The word before the adjective follows the definite-article pattern and already carries the grammar signal. The adjective therefore takes -${ending}.`,
    ruleEin: (ending: string) =>
      `The word before the adjective follows the indefinite-article pattern. The adjective takes -${ending} in this form.`,
    ruleQuantity: (ending: string) =>
      `A quantity word comes before the noun. The adjective takes -${ending} in this form.`,
    ruleZero: (ending: string) =>
      `There is no article, so the adjective carries the grammar signal: -${ending}.`,
  },
};

export const VERB_COPY = {
  [ELanguage.Russian]: {
    home: "Все тренажёры",
    stats: "Статистика",
    lifetime: "Всего правильных ответов",
    tagline: "Собери полную формулу немецкого глагола.",
    run: "забег",
    streak: "серия",
    typeMode: "ввод",
    choiceMode: "выбор",
    mixedNote: "Разные времена · вопросы · предлоги и возвратность",
    verb: "исходный глагол",
    placeholder: "Например: mich um",
    check: "Проверить",
    chooseReflexive: "Возвратное местоимение",
    choosePreposition: "Предлог",
    correct: "Точно! Формула собрана.",
    wrong: "Почти. В этой конструкции нужна другая связка.",
    yourAnswer: "Твой ответ",
    next: "Дальше",
    finish: "Результат",
    acc: "Akkusativ",
    dat: "Dativ",
    resultTitle: "Забег завершён.",
    resultSubtitle: "Вот как прошли эти десять глагольных конструкций.",
    accuracy: "точность",
    bestStreak: "лучшая серия",
    weakSpot: "Потренировать дальше",
    again: "Ещё один забег",
    statsTitle: "Статистика предлогов и возвратности",
    statsSubtitle: "Точность по каждой полной глагольной конструкции.",
    totalAnswers: "всего ответов",
    totalMistakes: "ошибок",
    patternsSeen: "встречалось конструкций",
    patterns: "Глагольные модели",
    correctShort: "верно",
    mistakesShort: "ошибок",
    prepErrors: "предлог",
    reflexiveErrors: "возвратность",
    reflexivePattern: "возвратный",
    plainPattern: "невозвратный",
    noAnswers: "Ответов пока нет",
    noAnswersHint:
      "Реши хотя бы одно задание — и здесь появится первая конструкция.",
    closeStats: "Закрыть статистику",
    statsNote:
      "Статистика хранится только на этом устройстве и обновляется после каждого ответа.",
    rulePlain: (frame: string) =>
      `${frame}. Предлог — часть устойчивой конструкции, а падеж задаётся всей связкой.`,
    ruleReflexive: (frame: string) =>
      `${frame}. Возвратное местоимение согласуется с подлежащим; предлог и падеж относятся ко всей конструкции.`,
  },
  [ELanguage.English]: {
    home: "All trainers",
    stats: "Statistics",
    lifetime: "Correct answers overall",
    tagline: "Build the complete pattern of a German verb.",
    run: "run",
    streak: "streak",
    typeMode: "type",
    choiceMode: "choose",
    mixedNote: "Mixed tenses · questions · prepositions and reflexivity",
    verb: "base verb",
    placeholder: "For example: mich um",
    check: "Check",
    chooseReflexive: "Reflexive pronoun",
    choosePreposition: "Preposition",
    correct: "Nailed it! The pattern is complete.",
    wrong: "Almost. This construction needs a different combination.",
    yourAnswer: "Your answer",
    next: "Next one",
    finish: "See results",
    acc: "Accusative",
    dat: "Dative",
    resultTitle: "Run complete.",
    resultSubtitle: "Here is how those ten verb patterns went.",
    accuracy: "accuracy",
    bestStreak: "best streak",
    weakSpot: "Train this next",
    again: "Start another run",
    statsTitle: "Verb Pattern Statistics",
    statsSubtitle: "Accuracy for every complete verb pattern.",
    totalAnswers: "total answers",
    totalMistakes: "mistakes",
    patternsSeen: "patterns encountered",
    patterns: "Verb patterns",
    correctShort: "correct",
    mistakesShort: "mistakes",
    prepErrors: "preposition",
    reflexiveErrors: "reflexivity",
    reflexivePattern: "reflexive",
    plainPattern: "non-reflexive",
    noAnswers: "No answers yet",
    noAnswersHint:
      "Complete at least one exercise and your first pattern will appear here.",
    closeStats: "Close statistics",
    statsNote:
      "Statistics stay on this device and update after every answer.",
    rulePlain: (frame: string) =>
      `${frame}. The preposition belongs to the verb pattern, and the construction determines the case.`,
    ruleReflexive: (frame: string) =>
      `${frame}. The reflexive pronoun agrees with the subject; the preposition and case belong to the whole pattern.`,
  },
};

export const PARTICIPLE_COPY = {
  [ELanguage.Russian]: {
    home: "Все тренажёры",
    stats: "Статистика",
    lifetime: "Всего правильных ответов",
    tagline: "Доведи форму Partizip II до автоматизма.",
    run: "забег",
    streak: "серия",
    mixedNote: "50 глаголов в круге · 3 контекста · интервальные повторы",
    infinitive: "инфинитив",
    placeholder: "Введи Partizip II",
    check: "Проверить",
    correct: "Точно! Форма на месте.",
    wrong: "Почти. Здесь нужна другая форма Partizip II.",
    yourAnswer: "Твой ответ",
    next: "Дальше",
    finish: "Результат",
    resultTitle: "Забег завершён.",
    resultSubtitle: "Вот как прошли эти десять форм Partizip II.",
    accuracy: "точность",
    bestStreak: "лучшая серия",
    weakSpot: "Потренировать дальше",
    again: "Ещё один забег",
    statsTitle: "Статистика Partizip II",
    statsSubtitle:
      "Общий прогресс, модели образования и последние результаты каждого глагола.",
    totalAnswers: "основных ответов",
    verbsSeen: "встречено глаголов",
    mastered: "усвоено",
    needsWork: "требуют отработки",
    groups: "Модели образования",
    verbs: "Все глаголы",
    search: "Найти глагол",
    attempts: "попыток",
    recent: "последние три",
    correctShort: "верно",
    noAnswers: "Ответов пока нет",
    noAnswersHint:
      "Реши хотя бы одно основное задание — и здесь появится первый глагол.",
    closeStats: "Закрыть статистику",
    statsNote:
      "Основная точность не меняется во время работы над ошибками и интервальных повторений.",
    weak: "Слабые",
    strong: "Сильные",
    mixed: "Смешанные",
    separable: "Отделяемые",
    inseparable: "Неотделяемые",
    ieren: "На -ieren",
    weakExample: "machen → gemacht",
    strongExample: "sehen → gesehen",
    mixedExample: "bringen → gebracht",
    separableExample: "anrufen → angerufen",
    inseparableExample: "verstehen → verstanden",
    ierenExample: "studieren → studiert",
    weakTag: "слабый",
    strongTag: "сильный",
    mixedTag: "смешанный",
    separableTag: "отделяемый",
    inseparableTag: "неотделяемый",
    ierenTag: "на -ieren",
    habenTag: "Perfekt с haben",
    seinTag: "Perfekt с sein",
    ruleWeak: "Слабый глагол сохраняет основу и обычно получает окончание -t.",
    ruleStrong:
      "Сильный глагол часто меняет основу и обычно получает окончание -en.",
    ruleMixed:
      "Смешанный глагол меняет основу, но получает окончание -t.",
    ruleSeparable:
      "У отделяемой приставки ge- встаёт между приставкой и основой.",
    ruleInseparable: "С неотделяемой приставкой ge- не добавляется.",
    ruleIeren: "Глаголы на -ieren образуют Partizip II без ge-.",
  },
  [ELanguage.English]: {
    home: "All trainers",
    stats: "Statistics",
    lifetime: "Correct answers overall",
    tagline: "Make Partizip II automatic.",
    run: "run",
    streak: "streak",
    mixedNote: "50 verbs per round · 3 contexts · spaced reviews",
    infinitive: "infinitive",
    placeholder: "Type the Partizip II form",
    check: "Check",
    correct: "Nailed it! The form fits.",
    wrong: "Almost. This sentence needs a different Partizip II form.",
    yourAnswer: "Your answer",
    next: "Next one",
    finish: "See results",
    resultTitle: "Run complete.",
    resultSubtitle: "Here is how those ten Partizip II forms went.",
    accuracy: "accuracy",
    bestStreak: "best streak",
    weakSpot: "Train this next",
    again: "Start another run",
    statsTitle: "Partizip II statistics",
    statsSubtitle:
      "Overall progress, formation patterns, and the latest results for each verb.",
    totalAnswers: "main answers",
    verbsSeen: "verbs encountered",
    mastered: "mastered",
    needsWork: "need review",
    groups: "Formation patterns",
    verbs: "All verbs",
    search: "Find a verb",
    attempts: "attempts",
    recent: "latest three",
    correctShort: "correct",
    noAnswers: "No answers yet",
    noAnswersHint:
      "Complete at least one main exercise and your first verb will appear here.",
    closeStats: "Close statistics",
    statsNote:
      "Main accuracy does not change during mistake review or spaced carry-over exercises.",
    weak: "Weak",
    strong: "Strong",
    mixed: "Mixed",
    separable: "Separable",
    inseparable: "Inseparable",
    ieren: "Ending in -ieren",
    weakExample: "machen → gemacht",
    strongExample: "sehen → gesehen",
    mixedExample: "bringen → gebracht",
    separableExample: "anrufen → angerufen",
    inseparableExample: "verstehen → verstanden",
    ierenExample: "studieren → studiert",
    weakTag: "weak",
    strongTag: "strong",
    mixedTag: "mixed",
    separableTag: "separable",
    inseparableTag: "inseparable",
    ierenTag: "ending in -ieren",
    habenTag: "Perfect with haben",
    seinTag: "Perfect with sein",
    ruleWeak: "A weak verb keeps its stem and usually takes the ending -t.",
    ruleStrong:
      "A strong verb often changes its stem and usually takes the ending -en.",
    ruleMixed: "A mixed verb changes its stem but takes the ending -t.",
    ruleSeparable:
      "With a separable prefix, ge- sits between the prefix and the stem.",
    ruleInseparable: "An inseparable prefix blocks ge-.",
    ruleIeren: "Verbs ending in -ieren form Partizip II without ge-.",
  },
};

export const REVIEW_COPY = {
  [ELanguage.Russian]: {
    trigger: "Ошибки",
    eyebrow: "ЗАКРЕПЛЕНИЕ",
    title: "Работа над ошибками",
    subtitle:
      "Сначала повторяем исходную ошибку, затем проверяем тот же навык на другом предложении.",
    active: "требуют повторения",
    mastered: "отработано",
    sourceStepTitle: "Исходная ошибка",
    sourceStepText: "Вернись к предложению, в котором была допущена ошибка.",
    analogueStepTitle: "Проверка навыка",
    analogueStepText: "Реши новое предложение с той же грамматической моделью.",
    start: "Начать отработку",
    emptyTitle: "Активных ошибок нет",
    emptyHint:
      "Новые ошибки из обычных забегов автоматически появятся здесь.",
    close: "Закрыть работу над ошибками",
    note: "Результаты этого режима не меняют основную статистику точности.",
    runLabel: "ошибки",
    sourceStep: "Шаг 1 из 2 · исходная ошибка",
    analogueStep: "Шаг 2 из 2 · аналогичное задание",
    added: "Добавлено в работу над ошибками.",
    sourceCorrect:
      "Первый шаг готов. Дальше появится другое задание на тот же навык.",
    sourceWrong: "Исходная ошибка остаётся на повторение.",
    analogueCorrect: "Навык закреплён — ошибка отработана.",
    analogueWrong:
      "Навык пока не закреплён. В следующий раз начнём с исходной ошибки.",
    resultTitle: "Отработка завершена.",
    resultSubtitle: "Ошибки прошли два шага: повтор и проверку навыка.",
    masteredThisRun: "отработано сейчас",
    continue: "Продолжить отработку",
    backToRegular: "Обычный забег",
  },
  [ELanguage.English]: {
    trigger: "Mistakes",
    eyebrow: "REINFORCEMENT",
    title: "Review mistakes",
    subtitle:
      "First repeat the original mistake, then prove the same skill in a different sentence.",
    active: "need review",
    mastered: "mastered",
    sourceStepTitle: "Original mistake",
    sourceStepText: "Return to the sentence where the mistake happened.",
    analogueStepTitle: "Skill check",
    analogueStepText: "Solve a new sentence built around the same grammar pattern.",
    start: "Start mistake review",
    emptyTitle: "No active mistakes",
    emptyHint:
      "New mistakes from regular runs will automatically appear here.",
    close: "Close mistake review",
    note: "Results from this mode do not change your main accuracy statistics.",
    runLabel: "mistakes",
    sourceStep: "Step 1 of 2 · original mistake",
    analogueStep: "Step 2 of 2 · similar exercise",
    added: "Added to mistake review.",
    sourceCorrect:
      "Step one is complete. A new exercise for the same skill comes next.",
    sourceWrong: "The original mistake stays in review.",
    analogueCorrect: "Skill confirmed — this mistake is mastered.",
    analogueWrong:
      "Not quite mastered yet. Next time you will restart from the original mistake.",
    resultTitle: "Review complete.",
    resultSubtitle:
      "Each mistake went through the repeat and skill-check steps.",
    masteredThisRun: "mastered now",
    continue: "Continue review",
    backToRegular: "Regular run",
  },
};
